## 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy (Numerical Python) is a fundamental package for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.
Advantages are:
* NumPy provides a powerful ndarray object for multi-dimensional arrays, enabling efficient storage and manipulation of large datasets.
* Includes a vast library of mathematical functions optimized for array operations, facilitating complex numerical computations.
* NumPy arrays are more memory efficient than Python lists for large datasets, due to their densely packed structure and optimized algorithms.
* Operations are implemented in compiled C code, making NumPy significantly faster than equivalent pure Python code.

## 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?


### np.mean()


Usage:
   Computes the arithmetic mean of elements in the array `a`.
   Works straightforwardly on arrays and can handle multi-dimensional arrays by averaging along specified axes.
  -If `axis=None`, computes the mean of the flattened array.

Example:
  ```python
  import numpy as np
  
  arr = np.array([[1, 2], [3, 4]])
  print(np.mean(arr))  # Output: 2.5
  ```

### np.average()

- **Usage:**
  - Calculates a weighted average where each element in the array may contribute differently to the average based on the provided weights.
  - Useful when certain elements in the array should have more influence on the computed average than others.
  - Can be applied to compute weighted averages over specific axes in multi-dimensional arrays.

Example:
  ```python
  import numpy as np
  
  arr = np.array([1, 2, 3, 4])
  weights = np.array([0.1, 0.2, 0.3, 0.4])
  
  print(np.average(arr, weights=weights))  # Output: 3.0
  ```

### Comparison and When to Use Each:

- **Mean (`np.mean()`):**
  - Computes the arithmetic mean of elements in an array.
  - Use when you need a straightforward average of values.
  - Does not require specifying weights; all elements contribute equally.

- **Average (`np.average()`):**
  - Computes a weighted average of elements in an array.
  - Use when different elements in the array have different importance or weight in the average calculation.
  - Allows for specifying weights, which can adjust the influence of each element on the final average.



## 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [3]:
#We reverse arrays using slicing process
import numpy as np

arr1d = np.array(['a','b','c','d','e'])

# Reverse the 1D array
reversed_arr1d = arr1d[::-1]

print("Original 1D Array:", arr1d)
print("Reversed 1D Array:", reversed_arr1d)


Original 1D Array: ['a' 'b' 'c' 'd' 'e']
Reversed 1D Array: ['e' 'd' 'c' 'b' 'a']


In [4]:

## reversing 2D array along rows
import numpy as np

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Reverse the 2D array along rows (axis 0)
reversed_arr2d_rows = arr2d[::-1, :]

print("Original 2D Array:")
print(arr2d)
print("\nReversed 2D Array along Rows:")
print(reversed_arr2d_rows)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reversed 2D Array along Rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [5]:
## reversing 2D array along columns
import numpy as np

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Reverse the 2D array along columns (axis 1)
reversed_arr2d_cols = arr2d[:, ::-1]

print("Original 2D Array:")
print(arr2d)
print("\nReversed 2D Array along Columns:")
print(reversed_arr2d_cols)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reversed 2D Array along Columns:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


## 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

In [8]:
## Determing the data type in Numpy

import numpy as  npp
arr = npp.array(['a','b','c','d','e'])
dtype = arr.dtype

print("The data type is",dtype)

The data type is <U1


Importance of Data Types
Memory Management:

- Data types dictate how much memory each element occupies. Choosing appropriate types (e.g., int32 vs float64) can significantly reduce memory usage, crucial for large datasets.Homogeneous data types in NumPy arrays allow for efficient memory allocation and access patterns.

- Performance:Data types influence the execution speed of operations. Operations on smaller data types (e.g., int32) are generally faster than on larger types (float64).NumPy operations are optimized for specific data types, ensuring efficient vectorized computations.

## 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

 ndarrays (n-dimensional arrays) in NumPy are data structures that store multi-dimensional arrays of homogeneous data types efficiently.
 
- Multi-dimensional: ndarrays can have multiple dimensions (1D, 2D, etc.), suitable for representing complex data structures like matrices.

- Homogeneous Data Types: All elements in an ndarray must have the same data type, ensuring efficient memory usage and optimized operations.

- Efficient Storage and Computation: ndarrays are stored in contiguous memory blocks, allowing fast access and efficient vectorized operations.

- Broadcasting: Supports broadcasting for operations on arrays of different shapes without explicit looping.

- Universal Functions (ufuncs): NumPy provides mathematical functions optimized for ndarrays, operating element-wise across arrays.

### Difference between List and Array:
- Homogeneity: ndarrays require uniform data types, whereas Python lists can hold elements of different types.

- Efficiency: ndarrays are more memory efficient and faster for numerical computations due to their specialized storage and optimized operations.

- Functionality: NumPy arrays offer extensive mathematical functions and operations compared to Python lists, which are general-purpose.

In [10]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Accessing elements and performing operations
print(arr[3])  # Accessing an element
print(arr.sum())  # Calculating sum of elements


4
15


## 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays outperform Python lists significantly for large-scale numerical operations due to their optimized storage, efficient operations, and broad library support. They are essential for tasks requiring high-performance computing, such as scientific computing, data analysis, and machine learning.


- NumPy Arrays: Contiguous memory allocation allows efficient storage and access, reducing overhead compared to Python lists which store pointers to objects.
- Python Lists: Each element is a full Python object with additional memory overhead, making them less efficient for large datasets.
 

- NumPy Arrays: Operations are optimized and vectorized, implemented in compiled C code. This results in faster execution times for numerical computations.
- Python Lists: Operations require explicit looping in Python, which is slower compared to NumPy's optimized operations.


- NumPy Arrays: Support element-wise operations and broadcasting, simplifying code and reducing the need for explicit loops.
- Python Lists: Operations often require manual iteration over elements, leading to more verbose code and slower execution times.

- NumPy Arrays: Integrated with a wide range of libraries (e.g., SciPy, pandas, scikit-learn) for scientific computing and data analysis, ensuring compatibility and optimized performance.
- Python Lists: More limited in terms of specialized numerical operations and library support, often requiring custom implementations for complex tasks.


## 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and  output.

The vstack() function in NumPy is used to vertically stack arrays, meaning it stacks arrays on top of each other along the vertical axis.

The hstack() function, on the other hand, horizontally stacks arrays, meaning it concatenates arrays side by side along the horizontal axis.

In [4]:
#code for vstack()
import numpy as np

# Create two arrays
array1 = np.array([['a','b','c'],
                   ['d','e','f']])

array2 = np.array([['@','#','$']])

# Vertically stack the arrays
result = np.vstack((array1, array2))

print(result)


[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['@' '#' '$']]


In [5]:
#code for vstack()
import numpy as np

# Create two arrays
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5],
                   [6]])

# Horizontally stack the arrays
result = np.hstack((array1, array2))

print(result)

[[1 2 5]
 [3 4 6]]


## 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In [18]:
# example of fliplr() methode

import numpy as np

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

flipped_arr = np.fliplr(arr2d)

print("Original 2D Array:")
print(arr2d)

print("\nFlipped Left-Right:")
print(flipped_arr)


Original 2D Array:
[[1 2 3]
 [4 5 6]]

Flipped Left-Right:
[[3 2 1]
 [6 5 4]]


In [19]:
# example of flipud() methode
import numpy as np

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

flipped_arr = np.flipud(arr2d)

print("Original 2D Array:")
print(arr2d)

print("\nFlipped Up-Down:")
print(flipped_arr)


Original 2D Array:
[[1 2 3]
 [4 5 6]]

Flipped Up-Down:
[[4 5 6]
 [1 2 3]]


#### Axis of Operation:

- fliplr() operates on columns (horizontal flip).
- flipud() operates on rows (vertical flip).

#### Usage:

- Use fliplr() when you need to reverse the order of columns.
- Use flipud() when you need to reverse the order of rows.

### 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

### 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

#### Vectorization:
Vectorization in NumPy refers to the process of applying operations to entire arrays (or matrices) instead of individual elements. It leverages the capabilities of modern CPUs and GPUs that can perform parallel operations on multiple data elements simultaneously.

- Vectorized operations are implemented in compiled C code under the hood in NumPy, making them much faster than equivalent operations implemented in pure Python.

- Vectorized code tends to be more concise and easier to read, as it eliminates the need for explicit looping constructs.

In [14]:
import numpy as np

# Example of vectorized addition
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

c = a + b  
print(c) 


[ 6  8 10 12]


#### Broadcasting 

is another powerful feature in NumPy that allows arrays of different shapes to be combined together for operations. It extends the capabilities of vectorized operations by implicitly replicating values as needed to perform compatible operations.

In [16]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

# Practical questions

## 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [32]:
## Solution
import numpy as np


arr = np.random.randint(1, 101,(3, 3))

print("Original Array:")
print(arr)

transposed_arr = np.transpose(arr)

print("\nTransposed Array (Interchanged rows and columns):")
print(transposed_arr)


Original Array:
[[22 88 62]
 [14  1 44]
 [27 89 54]]

Transposed Array (Interchanged rows and columns):
[[22 14 27]
 [88  1 89]
 [62 44 54]]


### 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [38]:
import numpy as np


arr1 = np.arange(10)  

print("1D Array:")
print(arr1)

# Step 2: Reshape into a 2x5 array
arr2x5 = arr1.reshape(2, 5)

print("\nReshaped into a 2x5 Array:")
print(arr2x5)

# Step 3: Reshape into a 5x2 array
arr5x2 = arr2x5.reshape(5, 2)

print("\nReshaped into a 5x2 Array:")
print(arr5x2)


1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into a 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into a 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [39]:
import numpy as np

# Step 1: Create a 4x4 NumPy array with random float values
arr_4x4 = np.random.rand(4, 4)

print("4x4 Array with random float values:")
print(arr_4x4)

# Step 2: Add a border of zeros around the 4x4 array to make it 6x6
# Initialize a 6x6 array filled with zeros
arr_6x6 = np.zeros((6, 6))

# Place the 4x4 array in the center of the 6x6 array
arr_6x6[1:5, 1:5] = arr_4x4

print("\n6x6 Array with zeros border:")
print(arr_6x6)


4x4 Array with random float values:
[[0.1031068  0.71205122 0.89616746 0.03332514]
 [0.58556953 0.05724964 0.66483989 0.54340731]
 [0.8780014  0.39899338 0.07926261 0.02078016]
 [0.62087352 0.71824479 0.47985442 0.25644636]]

6x6 Array with zeros border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.1031068  0.71205122 0.89616746 0.03332514 0.        ]
 [0.         0.58556953 0.05724964 0.66483989 0.54340731 0.        ]
 [0.         0.8780014  0.39899338 0.07926261 0.02078016 0.        ]
 [0.         0.62087352 0.71824479 0.47985442 0.25644636 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


## 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [7]:
## code 
import numpy as np


array = np.arange(10, 61, 5)

print(array)

[10 15 20 25 30 35 40 45 50 55 60]


##  5.  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [8]:
## code 
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
capitalize_array = np.char.capitalize(array)

print("Original Array:", array)
print("Uppercase Array:", uppercase_array)
print("Lowercase Array:", lowercase_array)
print("Titlecase Array:", titlecase_array)
print("Capitalize Array:", capitalize_array)

Original Array: ['python' 'numpy' 'pandas']
Uppercase Array: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase Array: ['python' 'numpy' 'pandas']
Titlecase Array: ['Python' 'Numpy' 'Pandas']
Capitalize Array: ['Python' 'Numpy' 'Pandas']


## 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

## 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [9]:
## code
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[100, 200], [300, 400]])
array2 = np.array([[500, 600], [700, 800]])

# Perform element-wise operations
add = array1 + array2
difference = array1 - array2
prod = array1 * array2
div = array1 / array2

print("Element-wise Addition:")
print(add)

print("\nElement-wise Subtraction:")
print(difference)

print("\nElement-wise Multiplication:")
print(prod)

print("\nElement-wise Division:")
print(div)

Element-wise Addition:
[[ 600  800]
 [1000 1200]]

Element-wise Subtraction:
[[-400 -400]
 [-400 -400]]

Element-wise Multiplication:
[[ 50000 120000]
 [210000 320000]]

Element-wise Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [10]:
## code
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


## 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

## 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [9]:
## code
import numpy as np

# Create a NumPy array of daily temperatures for a month (28 days for simplicity)
daily_temperatures = np.array([25, 27, 26, 28, 30, 29, 31, 32, 33, 31, 30, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

# Reshape the array to have 4 rows representing 4 weeks
weekly_temperatures = daily_temperatures.reshape(7,4)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

print(weekly_averages)

[26.5 30.5 30.5 25.5 21.5 17.5 13.5]
